// noinspection JSUnresolvedVariable
import { find } from 'lodash';

// Date/Time,Depth,,,Dissolved Oxygen,,,Dissolved Oxygen Percent,,,
// Acidity,,,Salinity,,,Specific Conductance,,,Turbidity,,,Water Temperature,,
export const params = {
  PWL: {
    param_type: 'hyd',
    param_code: 'PWL',
    param_nm: 'Pumping Water Level',
    unit: 'Meters',
  },
  ABSP: {
    param_type: 'hyd',
    param_code: 'ABSP',
    param_nm: 'Absolute Pressure',
    unit: 'psia',
  },
  COND: {
    param_type: 'hyd',
    param_code: 'COND',
    param_nm: 'Conductivity',
    unit: 'µS/cm',
  },
  CHL: {
    param_nm: 'Chlorophyll',
    usgs_code: '32315',
    param_type: 'hyd',
    unit: 'RFU',
  },
  FPC: {
    param_nm: 'Phycocyanin',
    usgs_code: '32315',
    param_type: 'hyd',
    unit: 'RFU',
  },
  CHLA: {
    param_type: 'hyd',
    param_code: 'CHLA',
    param_nm: 'Chlorophyll',
    unit: 'ug/L',
  },
  DEPTH: {
    param_type: 'hyd',
    nerrs_code: 'Depth',
    usgs_code: '62620',
    param_code: 'DEPTH',
    param_nm: 'Water Level',
    unit: 'Meters',
    conversion: unit => unit * 0.3048,
  },
  DO: {
    param_type: 'hyd',
    param_code: 'DO',
    usgs_code: '00300',
    nerrs_code: 'DO_mgl',
    param_nm: 'Dissolved Oxygen',
    unit: 'mg/L',
  },
  DOPC: {
    param_type: 'hyd',
    param_code: 'DOPC',
    usgs_code: '00301',
    param_nm: 'Dissolved Oxygen % Air Saturation',
    unit: '%',
  },
  ELEV: {
    param_type: 'hyd',
    usgs_code: '62620',
    param_code: 'ELEV',
    param_nm: 'Water Surface Elevation (relative to NAVD88)',
    unit: 'Meters',
    conversion: unit => unit * 0.3048,
  },
  PH: {
    param_type: 'hyd',
    param_code: 'PH',
    usgs_code: '00400',
    nerrs_code: 'pH',
    param_nm: 'Acidity',
    unit: 'pH',
  },
  SALT: {
    param_type: 'hyd',
    param_code: 'SALT',
    usgs_code: '90860',
    param_nm: 'Salinity',
    unit: 'ppt',
  },
  SPCO: {
    param_type: 'hyd',
    param_code: 'SPCO',
    usgs_code: '00095',
    nerrs_code: 'SpCond',
    param_nm: 'Conductivity',
    unit: 'µS/cm',
  },
  TURB: {
    param_type: 'hyd',
    param_code: 'TURB',
    usgs_code: '63680',
    nerrs_code: 'Turb',
    param_nm: 'Turbidity',
    unit: 'NTU',
  },
  WTMP: {
    param_type: 'hyd',
    param_code: 'WTMP',
    usgs_code: '00010',
    nerrs_code: 'Temp',
    param_nm: 'Water Temperature',
    conversion: unit => (unit * 1.8 + 32),
    unit: '°F',
  },
  ATMP: {
    param_type: 'met',
    param_code: 'ATMP',
    usgs_code: '00020',
    param_nm: 'Air Temperature',
    conversion: unit => (unit * 1.8 + 32),
    unit: '°F',
  },
  BARO: {
    param_type: 'met',
    param_code: 'BARO',
    usgs_code: '75969',
    param_nm: 'Barometric Pressure',
    unit: 'Millibars',
  },
  DEWP: {
    param_type: 'met',
    param_code: 'DEWP',
    param_nm: 'Dew Point',
    conversion: unit => (unit * 1.8 + 32),
    unit: '°F',
  },
  GST: {
    param_type: 'met',
    param_code: 'GST',
    param_nm: 'Wind Gust (15-minute max.)',
    unit: 'm/s',
  },
  PAR: {
    param_type: 'met',
    param_code: 'PAR',
    param_nm: 'Photosynthetically Active Radiation (PAR)',
    unit: 'mmoles/m^2',
  },
  RAD: {
    param_type: 'met',
    param_code: 'RAD',
    param_nm: 'Total Radiation',
    unit: 'Watts/m^2',
  },
  RAIN: {
    param_type: 'met',
    usgs_code: '00045',
    param_code: 'RAIN',
    param_nm: 'Rainfall',
    unit: 'mm',
  },
  RAINDC: {
    param_type: 'met',
    param_code: 'RAINDC',
    param_nm: 'Rainfall Daily Accumulation',
    unit: 'mm',
  },
  RHUM: {
    param_type: 'met',
    param_code: 'RHUM',
    param_nm: 'Relative Humidity',
    unit: '%',
  },
  STMP: {
    param_type: 'met',
    param_code: 'STMP',
    param_nm: 'Soil Temperature',
    conversion: unit => (unit * 1.8 + 32),
    unit: '°F',
  },
  WD: {
    param_type: 'met',
    param_code: 'WD',
    param_nm: 'Wind Direction',
    unit: 'Degrees',
  },
  WDEV: {
    param_type: 'met',
    param_code: 'WDEV',
    param_nm: 'Wind Direction Std. Dev.',
    unit: 'Degrees',
  },
  WSPD: {
    param_type: 'met',
    usgs_code: '82127',
    param_code: 'WSPD',
    param_nm: 'Wind Speed',
    unit: 'm/s',
  },
  WEATHER: {
    param_type: 'met',
    param_code: 'WSPD',
    usgs_code: '82127',
    param_nm: 'Weather',
    unit: 'm/s',
  },
};

export default params;
